"""Baseline: the schema as it stood at commit 831351e, before migrations existed.

Databases created by create_all() before this point are adopted by app/migrate.py:
brought up to this shape by the column stopgap, stamped 0001, then upgraded.

Revision ID: 0001
Revises: 
Create Date: 2026-09-24 09:26:12.856014+00:00
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('boundary', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_country_code'), ['code'], unique=True)

    op.create_table('audit_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_ref', sa.String(length=128), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('provenance', sa.String(length=32), nullable=False),
    sa.Column('confidence_marker', sa.String(length=2), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=96), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_entry_country_id'), ['country_id'], unique=False)

    op.create_table('connection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('system', sa.String(length=32), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('auth_type', sa.String(length=16), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('secret', sa.String(length=512), nullable=False),
    sa.Column('secret_env', sa.String(length=128), nullable=False),
    sa.Column('verify_tls', sa.Boolean(), nullable=False),
    sa.Column('timeout_s', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_ok', sa.Boolean(), nullable=True),
    sa.Column('last_test_detail', sa.JSON(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_summary', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_id', 'name', name='uq_connection_country_name')
    )
    with op.batch_alter_table('connection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connection_country_id'), ['country_id'], unique=False)

    op.create_table('node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('geocode_confidence', sa.Float(), nullable=False),
    sa.Column('geocode_source', sa.String(length=64), nullable=False),
    sa.Column('admin1', sa.String(length=128), nullable=True),
    sa.Column('admin2', sa.String(length=128), nullable=True),
    sa.Column('capacity', sa.JSON(), nullable=False),
    sa.Column('operating_status', sa.String(length=32), nullable=False),
    sa.Column('catchment_population', sa.Float(), nullable=False),
    sa.Column('terrain_class', sa.String(length=32), nullable=False),
    sa.Column('hub_capable', sa.Boolean(), nullable=False),
    sa.Column('hub_fixed_cost', sa.Float(), nullable=False),
    sa.Column('hub_open_capex', sa.Float(), nullable=False),
    sa.Column('hub_throughput_m3', sa.Float(), nullable=False),
    sa.Column('external_ids', sa.JSON(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_id', 'code', name='uq_node_country_code')
    )
    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_node_country_id'), ['country_id'], unique=False)
        batch_op.create_index('ix_node_country_level', ['country_id', 'level'], unique=False)

    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('temperature_band', sa.String(length=16), nullable=False),
    sa.Column('volume_per_unit_cm3', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('shelf_life_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_id', 'sku', name='uq_product_country_sku')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_country_id'), ['country_id'], unique=False)

    op.create_table('scenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('parent_scenario_id', sa.Integer(), nullable=True),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('levers', sa.JSON(), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=False),
    sa.Column('objective_weights', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_scenario_id'], ['scenario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_id', 'name', name='uq_scenario_country_name')
    )
    with op.batch_alter_table('scenario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenario_country_id'), ['country_id'], unique=False)

    op.create_table('demand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'product_id', 'period', name='uq_demand_node_product_period')
    )
    with op.batch_alter_table('demand', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_demand_country_id'), ['country_id'], unique=False)
        batch_op.create_index('ix_demand_node_product', ['node_id', 'product_id'], unique=False)

    op.create_table('edge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('from_node_id', sa.Integer(), nullable=False),
    sa.Column('to_node_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('base_travel_time_hr', sa.Float(), nullable=False),
    sa.Column('distance_method', sa.String(length=24), nullable=False),
    sa.Column('distance_confidence', sa.Float(), nullable=False),
    sa.Column('distance_note', sa.Text(), nullable=True),
    sa.Column('service_frequency', sa.String(length=16), nullable=True),
    sa.Column('service_days', sa.JSON(), nullable=True),
    sa.Column('service_name', sa.String(length=128), nullable=True),
    sa.Column('capacity_per_trip_m3', sa.Float(), nullable=False),
    sa.Column('cold_capacity_per_trip_m3', sa.Float(), nullable=False),
    sa.Column('fixed_cost_per_trip', sa.Float(), nullable=False),
    sa.Column('variable_cost_per_km', sa.Float(), nullable=False),
    sa.Column('cost_per_m3', sa.Float(), nullable=False),
    sa.Column('monthly_access', sa.JSON(), nullable=False),
    sa.Column('monthly_cost_multiplier', sa.JSON(), nullable=False),
    sa.Column('reliability', sa.Float(), nullable=False),
    sa.Column('lead_time_sd_days', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_node_id'], ['node.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_node_id'], ['node.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_id', 'code', name='uq_edge_country_code')
    )
    with op.batch_alter_table('edge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edge_country_id'), ['country_id'], unique=False)
        batch_op.create_index('ix_edge_from_to', ['from_node_id', 'to_node_id'], unique=False)

    op.create_table('import_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('committed', sa.Boolean(), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connection.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_batch', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_batch_country_id'), ['country_id'], unique=False)

    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('kpi_set', sa.JSON(), nullable=False),
    sa.Column('per_node_detail', sa.JSON(), nullable=False),
    sa.Column('per_edge_flow', sa.JSON(), nullable=False),
    sa.Column('equity_detail', sa.JSON(), nullable=False),
    sa.Column('solver_log', sa.JSON(), nullable=False),
    sa.Column('run_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('runtime_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_result_scenario_id'), ['scenario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_result_scenario_id'))

    op.drop_table('result')
    with op.batch_alter_table('import_batch', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_batch_country_id'))

    op.drop_table('import_batch')
    with op.batch_alter_table('edge', schema=None) as batch_op:
        batch_op.drop_index('ix_edge_from_to')
        batch_op.drop_index(batch_op.f('ix_edge_country_id'))

    op.drop_table('edge')
    with op.batch_alter_table('demand', schema=None) as batch_op:
        batch_op.drop_index('ix_demand_node_product')
        batch_op.drop_index(batch_op.f('ix_demand_country_id'))

    op.drop_table('demand')
    with op.batch_alter_table('scenario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenario_country_id'))

    op.drop_table('scenario')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_country_id'))

    op.drop_table('product')
    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.drop_index('ix_node_country_level')
        batch_op.drop_index(batch_op.f('ix_node_country_id'))

    op.drop_table('node')
    with op.batch_alter_table('connection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connection_country_id'))

    op.drop_table('connection')
    with op.batch_alter_table('audit_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_entry_country_id'))

    op.drop_table('audit_entry')
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_country_code'))

    op.drop_table('country')
    # ### end Alembic commands ###
